import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Button } from "@mui/material"
import React, { useContext, useEffect } from "react"
import { Context, ContextProvider } from "../ContextProvider"

import Link from "next/link"



export default function Home() {


  const { count, setCount } = useContext(Context)


  useEffect(function () {

    console.log("xxx")
    // console.log(requestAnimationFrame)


    function wrapCallingTime(fn) {

      let timeStamp = 0

      return function () {


        requestAnimationFrame(function (time) {

          if ((time - timeStamp) > 2000) {
            fn(time, timeStamp)
            timeStamp = time
          }
          else {
            console.log("not")
          }

        })


      }
    }

    const fn = wrapCallingTime((t, t2) => { console.log(t, t2, t - t2) })

    // setInterval(() => {
    //     fn()
    // }, 10);



  }, [])


  return (
    <div className={styles.container}>

      <Link href="/about"><h1>go to about {count}</h1></Link>
      <Button variant="contained" onClick={function () {
        setCount(pre => pre + 1)
      }}>add</Button>


      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
